### PR TITLE
Feature/friendship2

### PR DESCRIPTION
**Pull request by smcommits**
This PR adds the friendship-v2 feature. The friendship V2 feature is still the same mutual friendship feature but it has been implemented with a different approach. This PR uses two-row friendship creation to implement mutual friendship. The main aim of implementing a new approach is to achieve performance gains in terms of speed.

## Logical Approach

Instead of one single friendship model, two models one for FriendRequests and the other for Friendships has been created. Once the user sends a friend request, a FriendRequest record is created, and as soon as the other user accepts the friend request, a Friendship record is been created which will be corresponding to that request, and also a mirror record of the same friendship is also created to implement mutual friendship. Also, once accepted the request is destroyed using a service object called 'RequestDestroyer'. The simultaneous creation is being handled by transactions that are rescued by the standard error. If one will fail, both of the transaction will fail. 

## Associations

The changes made to the Associations are as follows:
- User has many recieved_friend_requests through FriendRequest class
- User has many sent_friend_request through FriendRequest class
- User has many friendships through the Friendships class

## Testing

The tests for querying the User model for pending requests and existence have been removed as now we are using two rows, and the queries are not required. 
Integration test has been added to test the Friendship controller's create action for validating the commitment of transaction with respect to valid attributes and invalid attributes.

### CODE REVIEW

**Comment by mimipeshy** [comment]
### STATUS : CHANGES REQUESTED :red_circle: :recycle: 
Hello Team @smcommits  👋

Great job on working on this project 👏 👏. This milestone has only one purpose. And it is to change the Friendship architecture in our application. ⏬
Make sure you read these links:

- [this article](https://explainextended.com/2009/03/07/selecting-friends)
- [StackOverflow discussion](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table)

Currently, when the friendship is confirmed, we are updating the confirmed column to true. But the requirement says:
 👉 when friendship is confirmed, an additional row with reversed user-friend pair is created
💡 I'll give you step by step guide to achieve this and more. ⏬

### Friendship model
* [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

* [ ] thanks to this, we can find user friends only by user_id in friendships table

```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

* [ ] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
* [ ] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

* [ ] in order to get all posts written by a user on their friends, you can use the simple method in the User model (in order to NOT do it with Enumerables)

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

- [ ]  PostsController#index displays posts in a timeline (their own posts + posts from their friends)([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))
- [ ] Add more unit and integration tests to your project

That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu
Feel free to reach out on slack if you have any questions

**Comment by smcommits** [comment]
@mimipeshy Thanks for the feedback! I am assuming you have mistakenly attempted to review a different branch. The functionality you are describing has been already implemented in the feature/friendshipv2 branch. It creates two rows upon confirmation and is implemented exactly as per the guidelines. I request you to please recheck the branch.

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @smcommits**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] It's true that most of these requirements are implemented. but if you look closely you will see that they are required to be in the friendship and user**Models** but you implementation is in the controllers. The reason that the previous CR asked for them to be added in the model is that Every query to the DB should be made in the models, that's why they exist. also it makes your app perform better by reducing the number of queries and keeping the controller code separated from the model code.
- [ ] Please make sure to implement the changes requested by the last Code reviewer before submitting another CRR.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @smcommits, I am Abdulaziz Redi Ali, your TSE for this PR.  👏👏  I appreciate your hard work.   Kindly fix the following issues.

[REQUIRED]

- [ ] Add integration test
- [ ] Add some examples to test files or remove them if they are not necessary. Don't submit empty test files.

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by layzrd — APPROVED** [review]
### Status: Approved 🙌 🎇
Hi @smcommits, I am  [Abdulaziz Redi Ali](https://azizali.ml/) again, your TSE for this PR.  Congratulations 🎊 👏, you did very well on this project.

Now, you can move ahead.

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Pull request merged**
